apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-task
  template:
    metadata:
      labels:
        app: docker-task
    spec:
      containers:
      - name: docker-task
        image: manojbj36/springboot-docker-task:latest
        ports:
        - containerPort: 80
